# --------------------------------------------------------------------------------------
#
#    ███████╗██████╗ ██████╗  █████╗ ██╗  ██╗███████╗███╗   ███╗██╗
#    ██╔════╝██╔══██╗██╔══██╗██╔══██╗██║  ██║██╔════╝████╗ ████║██║
#    █████╗  ██████╔╝██████╔╝███████║███████║█████╗  ██╔████╔██║██║
#    ██╔══╝  ██╔═══╝ ██╔══██╗██╔══██║██╔══██║██╔══╝  ██║╚██╔╝██║██║
#    ███████╗██║     ██║  ██║██║  ██║██║  ██║███████╗██║ ╚═╝ ██║██║
#    ╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝
#
#    Created by eprahemi
#    https://github.com/eprahemi/WifeRice
# --------------------------------------------------------------------------------------

general {
    lock_cmd = quickshell -p ~/.config/hypr/scripts/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ── Idle timeout: lock after 33 minutes ──
listener {
    timeout = 2000
    on-timeout = loginctl lock-session
}

# ── Idle timeout: suspend after 66 minutes ──
listener {
    timeout = 4000
    on-timeout = systemctl suspend
}
